
package br.com.github.GabrielRechBrand.integrationtjsc.tjsc;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "Exception", targetNamespace = "http://www.tjsc.jus.br/selo")
public class Exception_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Exception faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public Exception_Exception(String message, br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Exception faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public Exception_Exception(String message, br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Exception faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Exception
     */
    public br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Exception getFaultInfo() {
        return faultInfo;
    }

}
