
package br.com.github.GabrielRechBrand.integrationtjsc.tjsc;

import java.util.List;
import jakarta.activation.DataHandler;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.0
 * Generated source version: 3.0
 * 
 */
@WebService(name = "SeloService", targetNamespace = "http://www.tjsc.jus.br/selo")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SeloService {


    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.SituacaoTitulo>
     */
    @WebMethod
    @WebResult(name = "situacoesDeTitulo", targetNamespace = "")
    @RequestWrapper(localName = "getSituacoesDeTitulo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSituacoesDeTitulo")
    @ResponseWrapper(localName = "getSituacoesDeTituloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSituacoesDeTituloResponse")
    public List<SituacaoTitulo> getSituacoesDeTitulo();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoCobranca>
     */
    @WebMethod
    @WebResult(name = "tiposDeCobranca", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeCobranca", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeCobranca")
    @ResponseWrapper(localName = "getTiposDeCobrancaResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeCobrancaResponse")
    public List<TipoCobranca> getTiposDeCobranca();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoCobranca20>
     */
    @WebMethod
    @WebResult(name = "tiposDeCobranca20", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeCobranca20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeCobranca20")
    @ResponseWrapper(localName = "getTiposDeCobranca20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeCobranca20Response")
    public List<TipoCobranca20> getTiposDeCobranca20();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.JuizPaz>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "juizesDePaz", targetNamespace = "")
    @RequestWrapper(localName = "getJuizesDePaz", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetJuizesDePaz")
    @ResponseWrapper(localName = "getJuizesDePazResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetJuizesDePazResponse")
    public List<JuizPaz> getJuizesDePaz(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param nupedido
     * @param user
     * @param isento
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosPedido", targetNamespace = "")
    @RequestWrapper(localName = "getSelosPedido", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSelosPedido")
    @ResponseWrapper(localName = "getSelosPedidoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSelosPedidoResponse")
    public byte[] getSelosPedido(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "nupedido", targetNamespace = "")
        Long nupedido,
        @WebParam(name = "isento", targetNamespace = "")
        Boolean isento)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoSubestabelecimento>
     */
    @WebMethod
    @WebResult(name = "tiposDeSubestabelecimento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeSubestabelecimento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeSubestabelecimento")
    @ResponseWrapper(localName = "getTiposDeSubestabelecimentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeSubestabelecimentoResponse")
    public List<TipoSubestabelecimento> getTiposDeSubestabelecimento();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Banco>
     */
    @WebMethod
    @WebResult(name = "bancos", targetNamespace = "")
    @RequestWrapper(localName = "getBancos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetBancos")
    @ResponseWrapper(localName = "getBancosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetBancosResponse")
    public List<Banco> getBancos();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.CartorioLivro20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioLivros20", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioLivros20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartorioLivros20")
    @ResponseWrapper(localName = "getCartorioLivros20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartorioLivros20Response")
    public List<CartorioLivro20> getCartorioLivros20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Etnia>
     */
    @WebMethod
    @WebResult(name = "etnias", targetNamespace = "")
    @RequestWrapper(localName = "getEtnias", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEtnias")
    @ResponseWrapper(localName = "getEtniasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEtniasResponse")
    public List<Etnia> getEtnias();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoRegistroAverbacao>
     */
    @WebMethod
    @WebResult(name = "tiposDeRegistroDeAverbacao", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeRegistroDeAverbacao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeRegistroDeAverbacao")
    @ResponseWrapper(localName = "getTiposDeRegistroDeAverbacaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeRegistroDeAverbacaoResponse")
    public List<TipoRegistroAverbacao> getTiposDeRegistroDeAverbacao();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoTelefone>
     */
    @WebMethod
    @WebResult(name = "tiposDeTelefone", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeTelefone", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeTelefone")
    @ResponseWrapper(localName = "getTiposDeTelefoneResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeTelefoneResponse")
    public List<TipoTelefone> getTiposDeTelefone();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoTestamento>
     */
    @WebMethod
    @WebResult(name = "tiposDeTestamento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeTestamento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeTestamento")
    @ResponseWrapper(localName = "getTiposDeTestamentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeTestamentoResponse")
    public List<TipoTestamento> getTiposDeTestamento();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Comarca>
     */
    @WebMethod
    @WebResult(name = "comarcas", targetNamespace = "")
    @RequestWrapper(localName = "getComarcas", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetComarcas")
    @ResponseWrapper(localName = "getComarcasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetComarcasResponse")
    public List<Comarca> getComarcas();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoDocumento>
     */
    @WebMethod
    @WebResult(name = "tiposDeDocumento", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeDocumento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeDocumento")
    @ResponseWrapper(localName = "getTiposDeDocumentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeDocumentoResponse")
    public List<TipoDocumento> getTiposDeDocumento();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoAto>
     */
    @WebMethod
    @WebResult(name = "tiposDeAto", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeAto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeAto")
    @ResponseWrapper(localName = "getTiposDeAtoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeAtoResponse")
    public List<TipoAto> getTiposDeAto();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoSelo>
     */
    @WebMethod
    @WebResult(name = "tiposDeSelo", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeSelo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeSelo")
    @ResponseWrapper(localName = "getTiposDeSeloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeSeloResponse")
    public List<TipoSelo> getTiposDeSelo();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Moeda>
     */
    @WebMethod
    @WebResult(name = "moedas", targetNamespace = "")
    @RequestWrapper(localName = "getMoedas", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetMoedas")
    @ResponseWrapper(localName = "getMoedasResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetMoedasResponse")
    public List<Moeda> getMoedas();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.MotivoProtesto>
     */
    @WebMethod
    @WebResult(name = "motivosDeProtesto", targetNamespace = "")
    @RequestWrapper(localName = "getMotivosDeProtesto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetMotivosDeProtesto")
    @ResponseWrapper(localName = "getMotivosDeProtestoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetMotivosDeProtestoResponse")
    public List<MotivoProtesto> getMotivosDeProtesto();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.EstadoCivil>
     */
    @WebMethod
    @WebResult(name = "estadosCivis", targetNamespace = "")
    @RequestWrapper(localName = "getEstadosCivis", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEstadosCivis")
    @ResponseWrapper(localName = "getEstadosCivisResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEstadosCivisResponse")
    public List<EstadoCivil> getEstadosCivis();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Pais>
     */
    @WebMethod
    @WebResult(name = "paises", targetNamespace = "")
    @RequestWrapper(localName = "getPaises", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetPaises")
    @ResponseWrapper(localName = "getPaisesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetPaisesResponse")
    public List<Pais> getPaises();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Escolaridade>
     */
    @WebMethod
    @WebResult(name = "escolaridades", targetNamespace = "")
    @RequestWrapper(localName = "getEscolaridades", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEscolaridades")
    @ResponseWrapper(localName = "getEscolaridadesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEscolaridadesResponse")
    public List<Escolaridade> getEscolaridades();

    /**
     * 
     * @param messageIDtransmissao
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboTSRarmazenado", targetNamespace = "")
    @RequestWrapper(localName = "verificaTransmissao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.VerificaTransmissao")
    @ResponseWrapper(localName = "verificaTransmissaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.VerificaTransmissaoResponse")
    public byte[] verificaTransmissao(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "messageIDtransmissao", targetNamespace = "")
        Integer messageIDtransmissao)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.EspecieTitulo>
     */
    @WebMethod
    @WebResult(name = "especiesDeTitulo", targetNamespace = "")
    @RequestWrapper(localName = "getEspeciesDeTitulo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEspeciesDeTitulo")
    @ResponseWrapper(localName = "getEspeciesDeTituloResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEspeciesDeTituloResponse")
    public List<EspecieTitulo> getEspeciesDeTitulo();

    /**
     * 
     * @param pass
     * @param nupedido
     * @param user
     * @param isento
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosPedidoCompactados", targetNamespace = "")
    @RequestWrapper(localName = "getSelosPedidoCompactados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSelosPedidoCompactados")
    @ResponseWrapper(localName = "getSelosPedidoCompactadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSelosPedidoCompactadosResponse")
    public byte[] getSelosPedidoCompactados(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "nupedido", targetNamespace = "")
        Long nupedido,
        @WebParam(name = "isento", targetNamespace = "")
        Boolean isento)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.CartorioServentuario20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioServentuarios20", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioServentuarios20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartorioServentuarios20")
    @ResponseWrapper(localName = "getCartorioServentuarios20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartorioServentuarios20Response")
    public List<CartorioServentuario20> getCartorioServentuarios20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.MotivoCancelProtesto>
     */
    @WebMethod
    @WebResult(name = "motivosDeCancelamentoDoProtesto", targetNamespace = "")
    @RequestWrapper(localName = "getMotivosDeCancelamentoDoProtesto", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetMotivosDeCancelamentoDoProtesto")
    @ResponseWrapper(localName = "getMotivosDeCancelamentoDoProtestoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetMotivosDeCancelamentoDoProtestoResponse")
    public List<MotivoCancelProtesto> getMotivosDeCancelamentoDoProtesto();

    /**
     * 
     * @param recibo
     * @param pass
     * @param user
     * @return
     *     returns br.com.github.GabrielRechBrand.integrationtjsc.tjsc.ReciboProtocolo
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboDecodificado", targetNamespace = "")
    @RequestWrapper(localName = "decodificaRecibo", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.DecodificaRecibo")
    @ResponseWrapper(localName = "decodificaReciboResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.DecodificaReciboResponse")
    public ReciboProtocolo decodificaRecibo(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "recibo", targetNamespace = "")
        DataHandler recibo)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.JuizPaz20>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "juizesDePaz20", targetNamespace = "")
    @RequestWrapper(localName = "getJuizesDePaz20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetJuizesDePaz20")
    @ResponseWrapper(localName = "getJuizesDePaz20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetJuizesDePaz20Response")
    public List<JuizPaz20> getJuizesDePaz20(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoServentuario>
     */
    @WebMethod
    @WebResult(name = "tiposDeServentuario", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeServentuario", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeServentuario")
    @ResponseWrapper(localName = "getTiposDeServentuarioResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeServentuarioResponse")
    public List<TipoServentuario> getTiposDeServentuario();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.ComarcaMunicipio>
     */
    @WebMethod
    @WebResult(name = "comarcasmunicipios", targetNamespace = "")
    @RequestWrapper(localName = "getComarcasMunicipios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetComarcasMunicipios")
    @ResponseWrapper(localName = "getComarcasMunicipiosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetComarcasMunicipiosResponse")
    public List<ComarcaMunicipio> getComarcasMunicipios();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.CartorioServentuario>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioServentuarios", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioServentuarios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartorioServentuarios")
    @ResponseWrapper(localName = "getCartorioServentuariosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartorioServentuariosResponse")
    public List<CartorioServentuario> getCartorioServentuarios(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.CartorioLivro>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "cartorioLivros", targetNamespace = "")
    @RequestWrapper(localName = "getCartorioLivros", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartorioLivros")
    @ResponseWrapper(localName = "getCartorioLivrosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartorioLivrosResponse")
    public List<CartorioLivro> getCartorioLivros(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Profissao>
     */
    @WebMethod
    @WebResult(name = "profissoes", targetNamespace = "")
    @RequestWrapper(localName = "getProfissoes", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetProfissoes")
    @ResponseWrapper(localName = "getProfissoesResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetProfissoesResponse")
    public List<Profissao> getProfissoes();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Cartorio>
     */
    @WebMethod
    @WebResult(name = "cartorios", targetNamespace = "")
    @RequestWrapper(localName = "getCartorios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartorios")
    @ResponseWrapper(localName = "getCartoriosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetCartoriosResponse")
    public List<Cartorio> getCartorios();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Municipio>
     */
    @WebMethod
    @WebResult(name = "municipios", targetNamespace = "")
    @RequestWrapper(localName = "getMunicipios", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetMunicipios")
    @ResponseWrapper(localName = "getMunicipiosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetMunicipiosResponse")
    public List<Municipio> getMunicipios();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "numeroSelosLiberados", targetNamespace = "")
    @RequestWrapper(localName = "redisponibilizaUltimaTransmissaoSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.RedisponibilizaUltimaTransmissaoSelos")
    @ResponseWrapper(localName = "redisponibilizaUltimaTransmissaoSelosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.RedisponibilizaUltimaTransmissaoSelosResponse")
    public int redisponibilizaUltimaTransmissaoSelos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosCompactados", targetNamespace = "")
    @RequestWrapper(localName = "getSelosCompactados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSelosCompactados")
    @ResponseWrapper(localName = "getSelosCompactadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSelosCompactadosResponse")
    public byte[] getSelosCompactados(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoEndereco>
     */
    @WebMethod
    @WebResult(name = "tiposDeEndereco", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEndereco", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeEndereco")
    @ResponseWrapper(localName = "getTiposDeEnderecoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeEnderecoResponse")
    public List<TipoEndereco> getTiposDeEndereco();

    /**
     * 
     * @param pass
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "selosAssinados", targetNamespace = "")
    @RequestWrapper(localName = "getSelos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSelos")
    @ResponseWrapper(localName = "getSelosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetSelosResponse")
    public byte[] getSelos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoAto20>
     */
    @WebMethod
    @WebResult(name = "tiposDeAto20", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeAto20", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeAto20")
    @ResponseWrapper(localName = "getTiposDeAto20Response", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeAto20Response")
    public List<TipoAto20> getTiposDeAto20();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoProcuracao>
     */
    @WebMethod
    @WebResult(name = "tiposDeProcuracao", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeProcuracao", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeProcuracao")
    @ResponseWrapper(localName = "getTiposDeProcuracaoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeProcuracaoResponse")
    public List<TipoProcuracao> getTiposDeProcuracao();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoEndosso>
     */
    @WebMethod
    @WebResult(name = "tiposDeEndosso", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEndosso", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeEndosso")
    @ResponseWrapper(localName = "getTiposDeEndossoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeEndossoResponse")
    public List<TipoEndosso> getTiposDeEndosso();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.EnteDeclaradoUtilidadePublicaEstadual>
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "entesDeclaradosUtilidadePublicaEstadual", targetNamespace = "")
    @RequestWrapper(localName = "getEntesDeclaradosUtilidadePublicaEstadual", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEntesDeclaradosUtilidadePublicaEstadual")
    @ResponseWrapper(localName = "getEntesDeclaradosUtilidadePublicaEstadualResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEntesDeclaradosUtilidadePublicaEstadualResponse")
    public List<EnteDeclaradoUtilidadePublicaEstadual> getEntesDeclaradosUtilidadePublicaEstadual()
        throws Exception_Exception
    ;

    /**
     * 
     * @param pass
     * @param arquivo
     * @param user
     * @return
     *     returns byte[]
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(name = "reciboTSR", targetNamespace = "")
    @RequestWrapper(localName = "putAtos", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.PutAtos")
    @ResponseWrapper(localName = "putAtosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.PutAtosResponse")
    public byte[] putAtos(
        @WebParam(name = "user", targetNamespace = "")
        String user,
        @WebParam(name = "pass", targetNamespace = "")
        String pass,
        @WebParam(name = "arquivo", targetNamespace = "")
        DataHandler arquivo)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.Estado>
     */
    @WebMethod
    @WebResult(name = "estados", targetNamespace = "")
    @RequestWrapper(localName = "getEstados", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEstados")
    @ResponseWrapper(localName = "getEstadosResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetEstadosResponse")
    public List<Estado> getEstados();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.FormaPagamento>
     */
    @WebMethod
    @WebResult(name = "formasDePagamento", targetNamespace = "")
    @RequestWrapper(localName = "getFormasDePagamento", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetFormasDePagamento")
    @ResponseWrapper(localName = "getFormasDePagamentoResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetFormasDePagamentoResponse")
    public List<FormaPagamento> getFormasDePagamento();

    /**
     * 
     * @return
     *     returns java.util.List<br.com.github.GabrielRechBrand.integrationtjsc.tjsc.TipoEmail>
     */
    @WebMethod
    @WebResult(name = "tiposDeEmail", targetNamespace = "")
    @RequestWrapper(localName = "getTiposDeEmail", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeEmail")
    @ResponseWrapper(localName = "getTiposDeEmailResponse", targetNamespace = "http://www.tjsc.jus.br/selo", className = "br.com.github.GabrielRechBrand.integrationtjsc.tjsc.GetTiposDeEmailResponse")
    public List<TipoEmail> getTiposDeEmail();

}
